from pattern_to_number import PatternToNumber

def ComputingFrequency(Text, k):
    fqArr = [0] * (4**k)
    for i in range(len(Text) - k +1):
        pattern_number = PatternToNumber(Text[i: i+k])
        fqArr[pattern_number]+=1
        
    return fqArr
    
if __name__ == "__main__":
    Text = "ATCCTTTAGTACAGTATCTGTGGTGGACCGTGGGGGGAAGATAACCTTAAACTCGTGGATGCGTAACATGCCACTAAACGACGAACGCCTAGTTCCATCCAAGCGGGGTATGACAAGAAGACCATACAAAGGAGGAAACAGGTTACAGTTATAGGGGACGTCAAGGTAGCGACTACGACACTTTGGACCTCAATTCAGAACTGTCATTAATACCGTCGGATCTAAATGGGATCACGAGTATACAAGTTGACTATCATTGAGGCTGACGATAAGCACAAGAACATTGCAGTCCCTGGTACTCATTTGGGAGCCGTCCATTGTAGGACTGAGTCACAGTCGCCCATGTGAGCTCATGGAGAGCACTGAAAATGGCCTACACGGGCGCGCAAATTTGGGACATTGGCCCACCATGGCACCTTGAGGTACAGCTCACCGAGTTACCCTTCGATCGGAAGGGAAGTAACGAAATCGCACCTGTCCTCAGCCAGTCCGCCATGTGGTCACAGCAGTTTCTGCTTCCATTGCATGATGCCTACCTCGCGAAGGCACAACTCAGAGCGCAAGTACGCATTTCATCTTGGCATCCCGCCCATGAGTGTACTCTGCGTTTTTCGAGCTGGGAGCCTACTTGTGACTAC"
    print(ComputingFrequency(Text, 7))